server.port=8100
spring.application.name=electricity

# Correct MySQL configuration for aws
#spring.datasource.url=jdbc:mysql://lemonpayvas.cluster-cdie0w8k45f1.eu-north-1.rds.amazonaws.com/lemonpayvas?serverTimezone=UTC&useSSL=false
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.username=lemonpayvas
#spring.datasource.password=x~3OTFPrzNOD>LXbmKI[oP74-!?N

#spring.datasource.url=jdbc:mysql://203.161.48.99:3306/lemonpayvasdb?serverTimezone=UTC&useSSL=false
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.username=lemonpaydbuser
#spring.datasource.password=test

spring.datasource.url=jdbc:mysql://localhost:3306/lemonpayvasdb?serverTimezone=UTC&useSSL=false
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=Ugochukwu.1

# JPA & Hibernate configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.check_nullability=true

# Optional Hibernate SQL logging
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

#=============This section is for Redis==============
REDIS_URL=127.0.0.1
REDIS_PORT=6379
REDIS_PASSWORD=Ugochukwu.1
REDIS_USERNAME=ugochukwuomeje

spring.cloud.consul.host=127.0.0.1
spring.cloud.consul.port=8500
spring.cloud.consul.discovery.prefer-ip-address=true

#====================== this section is for Enugu============#
api-key=ae77a1d7c36fa732c4209bb40bce7469
secret-key=SK_956d29772cabfbc060d84fc122c55c007ed39a08025
public-key=PK_583cfdc6ce00a5daa66f0855c2d2e2729971965ff52
baseUrl=https://sandbox.vtpass.com/api
query=/merchant-verify
pay=/pay
requery=/requery
serviceId=enugu-electric



#spring:
#  application:
#    name: lemonpay-electricity
#
#  datasource:
#    url: jdbc:mysql://lemonpayvas.cluster-cdie0w8k45f1.eu-north-1.rds.amazonaws.com/lemonpayvas?serverTimezone=UTC&useSSL=false
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: lemonpayvas
#    password: x~3OTFPrzNOD>LXbmKI[oP74-!?N
#
#  jpa:
#    hibernate:
#      show-sql: true
#      ddl-auto: update
#      dialect: org.hibernate.dialect.MySQLDialect
#    show-sql: true
#
#server:
#  port: 6060
