FROM maven:3.9.6-eclipse-temurin-17 AS builder
WORKDIR /build
COPY . .

RUN cd phcnnode && mvn clean install
RUN cd lemonpayredis && mvn clean install
RUN cd eedc && mvn clean install
RUN mvn clean package -DskipTests

FROM eclipse-temurin:17-jdk-alpine
WORKDIR /app
COPY --from=builder /build/target/lemonpay-electricity-0.0.1-SNAPSHOT.jar app.jar
EXPOSE 8383
ENTRYPOINT ["java","-jar","app.jar"]
