spring.application.name=ikedc
api-key=ae77a1d7c36fa732c4209bb40bce7469
secret-key=SK_956d29772cabfbc060d84fc122c55c007ed39a08025
public-key=PK_583cfdc6ce00a5daa66f0855c2d2e2729971965ff52
baseUrl=https://sandbox.vtpass.com/api
verify=/merchant-verify
pay=/pay
requery=/requery
serviceId=ikeja-electric
