##spring.application.name=ikedc
##server.port=8585
#
#IKEDC_USERNAME=utilitiesgroup@etranzact.com
##IKEDC_PASSWROD=Covisions@1
#IKEDC_IDENTIFIER=etranzact
IKEDC_WALLET_ID=38889466
#IKEDC_BASEURL=http://197.253.19.78:1880/api/
IKEDC_BASEURL=https://api.pays-app.com
IKEDC_VERIFYENDPOINT=/confirm-ie-details
IKEDC_PAYMENTENDPOINT=/business/process-ie-transaction
IKEDC_ENCPIN_ENDPOINT=vas/credentials/encrypt-pin
IKEDC_AUTH=vas/authenticate/me
IKEDC_ECNCRYPTED_PIN=0476
IKEDC_CHANNEL=B2B
IKEDC_TOKEN=7883e2ec127225f478279f0cb848e3551eaaa99d484ec39cf0b77a9ccf1d9d0d
IKEDC_SIGNATURE_KEY=75ede3d5fff2047d96b07bc9f504c34c3ba0150ce9aa5bdbc3
IKEJA_DEFAULT_MOBILE=09087989094
MOBILE_START_WITH=04,02,03,05,06,00
IKEDC_BUSINESS_ID=CD8CB2
IKEDC_DEFAULT_NO=09087989094
IKEDC_PRODUCT_ID=1
IKEDC_REQUERY_ENDPOINT=/business/ref/
IKEDC_METER_NUMBER=12345678910